apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-secret
  namespace: ostadchess-prod
type: Opaque
data:
  # Username: admin
  # Password: ChessVector2024!
  # Generate with: htpasswd -bn admin 'ChessVector2024!' | base64
  auth: YWRtaW46JGFwcjEkT2dpams3dm8kUi9SZFppNW5pa0MzQkNnVzFsWHZLMQo=
