apiVersion: apps/v1
kind: Deployment
metadata:
  name: puzzle-service
spec:
  template:
    spec:
      containers:
        - name: puzzle
          envFrom:
            - secretRef:
                name: sentry-secret
