apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - postgres/
  - redis/
  - gateway-service/
  - puzzle-service/
  - stockfish-service/
  - eco-service/
  - opening-book-service/
  - import-service/
  - payment-service/
  - ui/

commonLabels:
  app.kubernetes.io/part-of: ostadchess
