apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: ostadchess-dev
type: Opaque
data:
  # admin:ChessVector2024!
  users: YWRtaW46JGFwcjEkT2dpams3dm8kUi9SZFppNW5pa0MzQkNnVzFsWHZLMQ==
