apiVersion: v1
kind: ServiceAccount
metadata:
  name: perf-smoke-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: perf-smoke-runner
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: perf-smoke-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: perf-smoke-runner
subjects:
  - kind: ServiceAccount
    name: perf-smoke-runner
    namespace: chess-staging
